### ISSUE TITLE
[BUG] Grid jittering/flickering

### ISSUE THREAD

**Issue by schroda** [petyosi/react-virtuoso#1086]
Found issue https://github.com/petyosi/react-virtuoso/issues/289 which looks similiar, but the trigger seems to be a bit different and it's also quite old

**Describe the bug**
In case the grid items have a dynamic height and the grid height itself is not larger than its items, the grid starts jittering/flickering once the scrollbar just barely appears.
The problem seems to be the scrollbar, that effects the width of the grid and thus, the height of the grid items.
In case the  browers scrollbar does not effect the width (e.g. firefox) or the height of the grid items is static, the issue does not occur.

**Reproduction**
https://codesandbox.io/p/sandbox/peaceful-aryabhata-wfdl75

**To Reproduce**
(see video)
1. Open https://codesandbox.io/p/sandbox/peaceful-aryabhata-wfdl75
2. Descrease browser window height until the scrollbar just barely appears
3. See error

**Expected behavior**
The scrollbar should appear without the grid going crazy

**Video**
[virtuoso_grid_jittering.webm](https://github.com/petyosi/react-virtuoso/assets/50052685/39e8173a-65a1-4c28-a137-da785e67c412)

**Desktop:**
 - OS: Windows 11, Ubuntu 22.04.4 LTS.
 - Browser: chromium
   - Microsoft Edge Version 124.0.2478.105 (Official Build) (64-Bit)
   - Version 125.0.6422.61 (Official Build) (64-Bit)

**Comment by petyosi** [comment]
That seems like a chicken and egg problem, but I think setting `overflow: scroll` should address it.

**Comment by leejunhui** [comment]
> That seems like a chicken and egg problem, but I think setting `overflow: scroll` should address it.

hi @petyosi , I also met the jittering issue when using VirtuosoGrid component. Please tell me where should I set the `overflow: scroll` style? Thanks a lot😂

**Comment by harrisrobin** [comment]
mine is jittery as well

**Comment by harrisrobin** [comment]
Ok, so i fixed my jittering/flickering by getting rid of margins entirely and using paddings on the item itself to space things out. 

I also gave every item a fixed height. This seems to have resolved all the jitter so that the grid can calculate things properly

**Comment by Simba-Mupfunya** [comment]
But this doesn't solve on variable height, the moment i use fixed height the issue is resolved but as all virtuoso components are meant to support variable height items, is there a way to resolve this for VirtuosoGrid

https://github.com/user-attachments/assets/e5258f09-276a-44af-88de-d8c006deaaf3
