### ISSUE TITLE
Support Server-Side Rendering

### ISSUE THREAD

**Issue by danielkov** [petyosi/react-virtuoso#21]
FIrst off, this is a great library and I've got into one of our projects with massive traffic, so it will be stress-tested.

When creating a bunch of examples I discovered that while it doesn't break SSR specifically, but there is no way to support the server at the moment. The effects it triggers don't run in a server environment, so the component comes out empty when rendered on the server. This makes sense when you consider the lack of an actual window on the server, however in most applications rendering at least some content is much better than coming back with nothing, especially for SEO purposes and data retention.

I am aware of the limitations when it comes to windowing and a windowless Node instance, so I'm proposing the following:

- Support SSR via a prop to declare amount of items to be rendered by default, or virtual window size to work with (maybe both, since both of these approaches have their pros and cons)
- Introduce a hydration phase, where the component can gracefully take over rendering in a window, when it reaches a browser.

I can help brainstorm ideas or even contribute code if you like as I know that this is a larger addition.

**Comment by petyosi** [comment]
Thanks for the suggestion. I don't have any experience with SSR specifics, but I think that this should be fairly easy to be implemented. 

Right now, the component relies on the resize observers to bring information about the viewport, item size, etc. in order to do the calculations and render the respective items. On the server, these are never triggered, as you stated.

However, if we somehow input the correct values (viewport height, some kind of item size) to the internal engine through the respective observers, the data should be rendered. Those can be injected through the props, I am already doing this in `getDerivedStateFromProps()`.

To help me with this, can you please point me to an example component which processes properties *exclusively* on the server? That would help me a lot. 

Cheers,

**Comment by danielkov** [comment]
There are two great ways to detect if a component is being rendered on the server:
1. Rely on the environment, like [this package does](https://www.npmjs.com/package/exenv). It's closely related to React internals so you can assume it's reliable.
2. Use React itself, more specifically, we know that `useEffect` only executes on the client, so we can create a hook taking advantage of this:

```js
const useIsServer = () => {
  const [isServer, setIsServer] = useState(true);
  useEffect(() => setIsServer(false), []);
}
```

The advantage of the first approach is that it doesn't rely on hooks, however it does rely on execution environment and that can be difficult to predict, for example some bundlers may chose to implement parts of `window` object to partially evaluate code and not run into `undefined` errors, which "might" make this unreliable.

The disadvantage of the second approach is that after the first pass it will evaluate to `true`, which may not be suitable for what you need.

I think a great approach would be to rely on the initial state (size, items, etc) provided by the consumer via props if present (because we can assume that they're present because the developer wants to use it for something like SSR). After the first pass, the effects will trigger and therefore take over rendering. This will also mediate the issue that comes up if you render something different on the server than what is rendered by the client in the first pass, which is the following error:
```
Warning: <XYZ> did not match. Server: <Value on server> Client: <Value on clientr>
```

**Comment by petyosi** [comment]
@danielkov I spiked a property called `initialItemCount`. If possible, can you build the library from the [SSR branch](https://github.com/petyosi/react-virtuoso/tree/ssr) and test it on your side? Essentially, all you have to do is set the property to the number of items you wish to get rendered initially, bypassing the DOM measurements. 

If it works in your environment, I am going to document it and publish a new version of the package.

**Comment by danielkov** [comment]
@petyosi do you know of a simple way to use it locally? When I do `file:` in `package.json` after building it mismatches React versions for some reason. I didn't have much time to fiddle with it, but if you have a good way to get it working I will try it.

**Comment by petyosi** [comment]
Sure, that would be something like this:
```sh
git clone git@github.com:petyosi/react-virtuoso.git virtuoso
git checkout ssr
cd virtuoso && yarn install && yarn build && yarn pack
```

Above should create  `react-virtuoso-v0.9.0.tgz` file in the repo.
Then, in your project, `yarn install path/to/lib/react-virtuoso-v0.9.0.tgz`

Cheers,

**Comment by petyosi** [comment]
@danielkov I just published v0.10 which includes the `initialItemCount` property, mentioned in the [API reference](https://virtuoso.dev/virtuoso-api-reference/). Let me know how it goes.

**Comment by danielkov** [comment]
@petyosi thanks for your effort, I've tested it out and it works nicely. Still throws a warning during SSR about `useLayoutEffect` not being able to render on server, but it renders the initial items nicely and hydrates correctly on first client render, so well done.

**Comment by petyosi** [comment]
Hm, I did not see that when testing in Gastby. Can you please let me know how I can reproduce that on my side? Thanks.

**Comment by danielkov** [comment]
@petyosi it will be different in Gatsby as it doesn't use SSR in a traditional way, but like I said it's fine because the warning shows it's working as intended. We don't want to have the effect take over and set the items in viewport during the server pass. If you'd like I can contribute with examples using Gatsby and NextJS.
